### ISSUE TITLE
Color for 'Append the circles' wrong

### ISSUE THREAD

**Issue by ru4ert** [quannh-netalik/radarchart-node#2]
Current:
The circle color don't match the colour of the strokes
![image](https://user-images.githubusercontent.com/47078678/136192127-d1a5cc0e-2466-4642-ba99-8fd4047a3e98.png)

Expected:
![image](https://user-images.githubusercontent.com/47078678/136192204-88c7be02-9f33-4e9d-b524-50bd60dbb48c.png)

I already fixed this, the pull requests follows!

**Comment by quannh-netalik** [comment]
Hello @Rupert-com ,

**Comment by quannh-netalik** [comment]
Hi @Rupert-com ,

Thank you for noticing and fixing this bug.
